In [1]:
import pandas as pd
import json
import os
from platform import python_version

In [2]:
directory = os.getcwd()

In [3]:
print(directory)

/root/dataviz/dataviz_project/data

In [4]:
content_of_directory = os.listdir("/root/dataviz/dataviz_project/data")
print(content_of_directory)

['SUIS.csv', 'USA.csv', 'CANADA.csv', 'Untitled.ipynb', 'germany.csv', '.ipynb_checkpoints']

In [5]:
dfSUIS = pd.read_csv("/root/dataviz/dataviz_project/data/SUIS.csv")
dfUSA = pd.read_csv("/root/dataviz/dataviz_project/data/USA.csv")
dfCANADA = pd.read_csv("/root/dataviz/dataviz_project/data/CANADA.csv")
dfgermany = pd.read_csv("/root/dataviz/dataviz_project/data/germany.csv")

In [11]:
dfSUIS

,Cancer site,5,10,15,20,25,30,35,40,45,50,55,60,65,70,75,80,85
0,Lip oral cavity and pharynx,0.10,0.20,0.19,0.65,1.20,1.30,2.20,3.90,7.80,13.2,20.60,22.8,24.10,20.90,20.3,19.70,27.00
1,Oesophagus,0.00,0.00,0.00,0.00,0.00,0.07,0.21,0.35,1.30,3.4,5.90,9.4,9.10,11.70,11.1,17.80,23.00
2,Stomach,0.00,0.00,0.10,0.28,0.42,0.97,1.90,4.10,5.20,6.3,9.60,12.3,18.70,25.50,36.8,47.50,60.90
3,Colorectum,0.20,0.69,0.87,1.00,2.90,2.90,5.50,13.70,22.90,41.7,63.00,87.5,125.90,157.40,210.8,262.10,283.90
4,Colon,0.20,0.59,0.87,1.00,1.80,1.90,3.20,8.20,13.10,21.7,34.30,52.3,75.10,103.90,143.5,189.20,198.20
5,Rectum and anus,0.00,0.10,0.00,0.00,1.00,1.00,2.40,5.50,9.80,20.0,28.70,35.2,50.80,53.50,67.3,72.90,85.80
6,Liver,0.00,0.10,0.29,0.19,0.08,0.37,0.42,0.98,1.90,4.6,5.50,8.1,13.80,19.30,25.3,22.50,21.20
7,Gallbladder etc.,0.00,0.00,0.00,0.09,0.00,0.07,0.14,0.42,1.00,2.2,4.60,5.7,11.40,17.20,24.8,30.30,30.80
8,Pancreas,0.00,0.00,0.19,0.09,0.08,0.30,0.69,2.00,3.50,7.3,14.00,22.6,31.40,49.50,72.2,94.30,104.10
9,Larynx,0.00,0.00,0.00,0.00,0.00,0.00,0.21,0.21,1.00,1.9,3.40,3.1,3.80,4.00,3.5,3.80,3.10
10,Lung,0.10,0.00,0.29,0.47,1.00,1.10,3.10,8.70,22.00,40.5,63.30,89.9,115.40,131.20,133.9,125.00,81.40
11,Melanoma of skin,0.10,0.79,2.80,11.50,15.60,20.90,23.70,27.80,31.80,33.7,41.50,44.6,47.70,55.90,53.4,55.90,55.30
12,Kaposi sarcoma,0.00,0.00,0.00,0.19,0.50,0.52,0.28,0.07,0.15,0.0,0.18,0.3,0.34,0.78,0.3,0.57,0.91
13,Breast,0.00,0.00,0.19,0.65,6.60,24.70,59.00,115.00,195.00,244.7,285.50,344.8,390.70,354.90,347.5,354.40,334.70
14,Cervix uteri,0.00,0.20,0.10,0.56,3.40,6.50,8.50,9.30,9.90,7.9,9.40,8.0,9.80,10.20,12.6,12.90,17.00
15,Uterus,0.00,0.20,0.10,0.75,3.80,8.00,11.30,13.90,22.00,33.3,53.70,66.5,83.10,91.60,95.7,87.30,79.00
16,Corpus uteri,0.00,0.00,0.00,0.19,0.34,1.50,2.60,4.30,11.80,24.2,42.40,56.2,71.30,79.00,79.9,71.40,54.80
17,Ovary,0.10,0.89,1.60,0.65,1.30,1.70,3.30,6.40,12.70,20.2,28.40,35.3,47.80,55.60,53.0,54.50,51.70
18,Multiple myeloma,0.00,0.00,0.00,0.00,0.08,0.37,0.83,0.84,2.80,3.9,6.10,10.0,16.80,23.90,30.6,34.50,25.90
19,Leukaemia,3.00,2.00,1.60,0.93,1.20,2.10,2.60,3.70,4.80,7.6,9.90,16.6,22.70,29.40,35.5,47.00,49.70
20,Kidney,0.41,0.30,0.19,0.47,0.25,0.52,1.10,1.90,4.20,5.6,9.30,14.4,18.20,24.30,28.1,31.60,24.10
21,Bladder,0.00,0.00,0.10,0.09,0.17,0.45,0.55,1.40,3.90,8.2,13.20,25.4,32.90,40.30,53.1,60.40,64.40
22,Brain and central nervous system,2.70,1.30,1.40,1.20,2.40,2.40,2.90,3.10,5.80,7.0,9.40,12.7,14.90,14.10,19.8,17.40,14.50
23,Thyroid,0.00,0.30,2.00,5.20,7.20,10.60,13.70,15.90,16.00,16.5,16.80,16.4,17.00,16.40,11.5,11.40,10.00
24,Hodgkin lymphoma,0.10,1.50,6.00,6.90,4.50,3.90,2.50,2.10,1.00,1.3,1.80,1.6,3.60,3.30,5.3,2.50,2.20
25,Non-Hodgkin lymphoma,0.31,0.98,1.20,1.70,2.10,3.30,4.60,6.20,10.60,13.6,22.50,31.0,42.00,54.80,70.7,72.00,60.90

In [9]:
dfSUIS.describe()

,5,10,15,20,25,30,35,40,45,50,55,60,65,70,75,80,85
count,26.000000,26.000000,26.000000,26.000000,26.000000,26.000000,26.000000,26.000000,26.000000,26.000000,26.000000,26.000000,26.000000,26.000000,26.000000,26.000000,26.000000
mean,0.281538,0.390000,0.772308,1.336538,2.227692,3.747692,6.055000,9.998846,16.228846,22.711538,30.883846,39.719231,49.936154,55.714615,63.326923,69.187308,67.865769
std,0.764809,0.547949,1.307187,2.611104,3.376535,6.195878,12.007767,22.325791,37.374462,46.906497,55.162379,67.070548,77.118052,73.030227,76.174597,83.069918,82.586546
min,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.140000,0.070000,0.150000,0.000000,0.180000,0.300000,0.340000,0.780000,0.300000,0.570000,0.910000
25%,0.000000,0.000000,0.025000,0.115000,0.190000,0.467500,0.725000,1.525000,2.975000,4.850000,6.900000,9.550000,14.075000,16.600000,19.925000,18.275000,21.650000
50%,0.000000,0.150000,0.190000,0.515000,1.100000,1.400000,2.550000,4.000000,6.800000,8.050000,13.600000,19.600000,23.400000,27.450000,36.150000,47.250000,50.700000
75%,0.100000,0.665000,1.117500,0.982500,2.775000,3.200000,4.275000,8.575000,13.000000,21.325000,32.900000,42.275000,50.050000,55.825000,71.825000,72.675000,75.350000
max,3.000000,2.000000,6.000000,11.500000,15.600000,24.700000,59.000000,115.000000,195.000000,244.700000,285.500000,344.800000,390.700000,354.900000,347.500000,354.400000,334.700000

In [16]:
import pandas as pd

# Function to rank the top 5 cancer sites for each age group
def rank_top_cancers(data):
    # Create an empty list to store the rankings
    rankings_list = []

    # Loop through each age group
    for age_group in data.columns[1:]:
        # Sort the cancer sites based on crude rate values in descending order
        sorted_cancers = data[['Cancer site', age_group]].sort_values(by=age_group, ascending=False)

        # Take the top 5 cancer sites
        top_5_cancers = sorted_cancers.head(5)['Cancer site'].tolist()

        # Append the rankings to the list
        rankings_list.append({'AgeGroup': age_group, '1st': top_5_cancers[0], '2nd': top_5_cancers[1],
                              '3rd': top_5_cancers[2], '4th': top_5_cancers[3], '5th': top_5_cancers[4]})

    # Create a DataFrame from the list
    rankings = pd.DataFrame(rankings_list)

    return rankings

# Assuming your data is stored in a DataFrame named 'dfSUIS'
rankings = rank_top_cancers(dfSUIS)

# Display the rankings
rankings

,AgeGroup,1st,2nd,3rd,4th,5th
0,5,Leukaemia,Brain and central nervous system,Kidney,Non-Hodgkin lymphoma,Colon
1,10,Leukaemia,Hodgkin lymphoma,Brain and central nervous system,Non-Hodgkin lymphoma,Ovary
2,15,Hodgkin lymphoma,Melanoma of skin,Thyroid,Ovary,Leukaemia
3,20,Melanoma of skin,Hodgkin lymphoma,Thyroid,Non-Hodgkin lymphoma,Brain and central nervous system
4,25,Melanoma of skin,Thyroid,Breast,Hodgkin lymphoma,Uterus
5,30,Breast,Melanoma of skin,Thyroid,Uterus,Cervix uteri
6,35,Breast,Melanoma of skin,Thyroid,Uterus,Cervix uteri
7,40,Breast,Melanoma of skin,Thyroid,Uterus,Colorectum
8,45,Breast,Melanoma of skin,Colorectum,Lung,Uterus
9,50,Breast,Colorectum,Lung,Melanoma of skin,Uterus
10,55,Breast,Lung,Colorectum,Uterus,Corpus uteri
11,60,Breast,Lung,Colorectum,Uterus,Corpus uteri
12,65,Breast,Colorectum,Lung,Uterus,Colon
13,70,Breast,Colorectum,Lung,Colon,Uterus
14,75,Breast,Colorectum,Colon,Lung,Uterus
15,80,Breast,Colorectum,Colon,Lung,Pancreas
16,85,Breast,Colorectum,Colon,Pancreas,Rectum and anus

In [19]:
import pandas as pd

def rank_top_cancers_combined(dataframes):
    # Create an empty list to store the rankings
    rankings_list = []

    # Loop through each dataframe in the list
    for df in dataframes:
        # Loop through each age group in the dataframe
        for age_group in df.columns[1:]:
            # Sort the cancer sites based on crude rate values in descending order
            sorted_cancers = df[['Cancer site', age_group]].sort_values(by=age_group, ascending=False)

            # Take the top 5 cancer sites
            top_5_cancers = sorted_cancers.head(5)['Cancer site'].tolist()

            # Append the rankings to the list
            rankings_list.append({'AgeGroup': age_group, '1st': top_5_cancers[0], '2nd': top_5_cancers[1],
                                  '3rd': top_5_cancers[2], '4th': top_5_cancers[3], '5th': top_5_cancers[4],
                                  'Dataset': df.name})  # Add the dataset name

    # Create a DataFrame from the list
    rankings = pd.DataFrame(rankings_list)

    return rankings

# Assuming your dataframes are named dfSUIS, dfUSA, dfCANADA, and dfgermany
# Add names to the dataframes
dfSUIS.name = 'SUIS'
dfUSA.name = 'USA'
dfCANADA.name = 'CANADA'
dfgermany.name = 'Germany'

# Combine the rankings from multiple dataframes
combined_rankings = rank_top_cancers_combined([dfSUIS, dfUSA, dfCANADA, dfgermany])

# Display the combined rankings
combined_rankings

,AgeGroup,1st,2nd,3rd,4th,5th,Dataset
0,5,Leukaemia,Brain and central nervous system,Kidney,Non-Hodgkin lymphoma,Colon,SUIS
1,10,Leukaemia,Hodgkin lymphoma,Brain and central nervous system,Non-Hodgkin lymphoma,Ovary,SUIS
2,15,Hodgkin lymphoma,Melanoma of skin,Thyroid,Ovary,Leukaemia,SUIS
3,20,Melanoma of skin,Hodgkin lymphoma,Thyroid,Non-Hodgkin lymphoma,Brain and central nervous system,SUIS
4,25,Melanoma of skin,Thyroid,Breast,Hodgkin lymphoma,Uterus,SUIS
...,...,...,...,...,...,...,...
64,70,All sites excl. non-melanoma skin cancer,Breast,Colorectum,Colon,Lung,Germany
65,75,All sites excl. non-melanoma skin cancer,Breast,Colorectum,Colon,Lung,Germany
66,80,All sites excl. non-melanoma skin cancer,Colorectum,Breast,Colon,Lung,Germany
67,85,All sites excl. non-melanoma skin cancer,Colorectum,Breast,Colon,Rectum and anus,Germany
68,Unnamed: 18,All sites excl. non-melanoma skin cancer,Lip oral cavity and pharynx,Oesophagus,Stomach,Colorectum,Germany